title: Métodos Numéricos PM 311 / 2026-II
description: Página web del curso PM 311 / 2026-II
sitename: PM 311
baseurl: 'pm-311.github.io'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - vendor
  - vendor/bundle
markdown: kramdown

theme: jekyll-theme-cayman
